import { defineField, defineType } from "sanity";

export const contactPage = defineType({
  name: "contactPage",
  title: "Stránka — Kontakt",
  type: "document",
  fields: [
    defineField({ name: "labelSk", title: "Label (SK)", type: "string" }),
    defineField({ name: "labelEn", title: "Label (EN)", type: "string" }),
    defineField({ name: "titleSk", title: "Nadpis (SK)", type: "string" }),
    defineField({ name: "titleEn", title: "Title (EN)", type: "string" }),
    defineField({ name: "subtitleSk", title: "Podnadpis (SK)", type: "text", rows: 2 }),
    defineField({ name: "subtitleEn", title: "Subtitle (EN)", type: "text", rows: 2 }),
    defineField({ name: "sentSk", title: "Odoslané (SK)", type: "string" }),
    defineField({ name: "sentEn", title: "Sent (EN)", type: "string" }),
    defineField({ name: "formNameSk", title: "Form — Meno (SK)", type: "string" }),
    defineField({ name: "formNameEn", title: "Form — Name (EN)", type: "string" }),
    defineField({ name: "formEmailSk", title: "Form — E-mail (SK)", type: "string" }),
    defineField({ name: "formEmailEn", title: "Form — Email (EN)", type: "string" }),
    defineField({ name: "formPhoneSk", title: "Form — Telefón (SK)", type: "string" }),
    defineField({ name: "formPhoneEn", title: "Form — Phone (EN)", type: "string" }),
    defineField({ name: "formEventTypeSk", title: "Form — Typ eventu (SK)", type: "string" }),
    defineField({ name: "formEventTypeEn", title: "Form — Event type (EN)", type: "string" }),
    defineField({ name: "formPackageSk", title: "Form — Balík (SK)", type: "string" }),
    defineField({ name: "formPackageEn", title: "Form — Package (EN)", type: "string" }),
    defineField({ name: "formMessageSk", title: "Form — Správa (SK)", type: "string" }),
    defineField({ name: "formMessageEn", title: "Form — Message (EN)", type: "string" }),
    defineField({ name: "formNamePlaceholderSk", title: "Placeholder meno (SK)", type: "string" }),
    defineField({ name: "formNamePlaceholderEn", title: "Name placeholder (EN)", type: "string" }),
    defineField({ name: "formEmailPlaceholderSk", title: "Placeholder e-mail (SK)", type: "string" }),
    defineField({ name: "formEmailPlaceholderEn", title: "Email placeholder (EN)", type: "string" }),
    defineField({ name: "formPhonePlaceholderSk", title: "Placeholder telefón (SK)", type: "string" }),
    defineField({ name: "formPhonePlaceholderEn", title: "Phone placeholder (EN)", type: "string" }),
    defineField({ name: "formMessagePlaceholderSk", title: "Placeholder správa (SK)", type: "string" }),
    defineField({ name: "formMessagePlaceholderEn", title: "Message placeholder (EN)", type: "string" }),
    defineField({ name: "formSubmitSk", title: "Odoslať (SK)", type: "string" }),
    defineField({ name: "formSubmitEn", title: "Submit (EN)", type: "string" }),
    defineField({ name: "formSubmittingSk", title: "Odosielam (SK)", type: "string" }),
    defineField({ name: "formSubmittingEn", title: "Submitting (EN)", type: "string" }),
    defineField({
      name: "formSegmentsSk",
      title: "Segmenty v selecte (SK)",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "formSegmentsEn",
      title: "Segments in select (EN)",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "formPackagesSk",
      title: "Balíky v selecte (SK)",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "formPackagesEn",
      title: "Packages in select (EN)",
      type: "array",
      of: [{ type: "string" }],
    }),
  ],
  preview: { prepare: () => ({ title: "Kontakt" }) },
});
