import { defineField, defineType } from "sanity";
import { pricingSegmentFields } from "./shared";

export const pricingPage = defineType({
  name: "pricingPage",
  title: "Stránka — Cenník",
  type: "document",
  fields: [
    defineField({ name: "labelSk", title: "Label (SK)", type: "string" }),
    defineField({ name: "labelEn", title: "Label (EN)", type: "string" }),
    defineField({ name: "titleSk", title: "Nadpis (SK)", type: "string" }),
    defineField({ name: "titleEn", title: "Title (EN)", type: "string" }),
    defineField({ name: "subtitleSk", title: "Podnadpis (SK)", type: "text", rows: 2 }),
    defineField({ name: "subtitleEn", title: "Subtitle (EN)", type: "text", rows: 2 }),
    defineField({ name: "noteSk", title: "Poznámka (SK)", type: "text", rows: 2 }),
    defineField({ name: "noteEn", title: "Note (EN)", type: "text", rows: 2 }),
    defineField({ name: "interestedSk", title: "Tlačidlo — Mám záujem (SK)", type: "string" }),
    defineField({ name: "interestedEn", title: "Button — Interested (EN)", type: "string" }),
    defineField({ name: "inquiryLabelSk", title: "Dopyt label (SK)", type: "string" }),
    defineField({ name: "inquiryLabelEn", title: "Inquiry label (EN)", type: "string" }),
    defineField({ name: "inquiryPackageSk", title: "Dopyt — balík (SK)", type: "string" }),
    defineField({ name: "inquiryPackageEn", title: "Inquiry package (EN)", type: "string" }),
    defineField({ name: "inquirySubtitleSk", title: "Dopyt podnadpis (SK)", type: "text", rows: 2 }),
    defineField({ name: "inquirySubtitleEn", title: "Inquiry subtitle (EN)", type: "text", rows: 2 }),
    defineField({ name: "sentSk", title: "Odoslané (SK)", type: "string" }),
    defineField({ name: "sentEn", title: "Sent (EN)", type: "string" }),
    defineField({
      name: "formNameSk",
      title: "Form — Meno (SK)",
      type: "string",
    }),
    defineField({ name: "formNameEn", title: "Form — Name (EN)", type: "string" }),
    defineField({ name: "formEmailSk", title: "Form — E-mail (SK)", type: "string" }),
    defineField({ name: "formEmailEn", title: "Form — Email (EN)", type: "string" }),
    defineField({ name: "formPhoneSk", title: "Form — Telefón (SK)", type: "string" }),
    defineField({ name: "formPhoneEn", title: "Form — Phone (EN)", type: "string" }),
    defineField({ name: "formMessageSk", title: "Form — Správa (SK)", type: "string" }),
    defineField({ name: "formMessageEn", title: "Form — Message (EN)", type: "string" }),
    defineField({ name: "formMessagePlaceholderSk", title: "Form — placeholder správy (SK)", type: "string" }),
    defineField({ name: "formMessagePlaceholderEn", title: "Form — message placeholder (EN)", type: "string" }),
    defineField({ name: "formSubmitSk", title: "Form — Odoslať (SK)", type: "string" }),
    defineField({ name: "formSubmitEn", title: "Form — Submit (EN)", type: "string" }),
    defineField({ name: "formCancelSk", title: "Form — Zrušiť (SK)", type: "string" }),
    defineField({ name: "formCancelEn", title: "Form — Cancel (EN)", type: "string" }),
    defineField({
      name: "segments",
      title: "Segmenty a balíky",
      type: "array",
      of: [{ type: "object", fields: pricingSegmentFields }],
    }),
  ],
  preview: { prepare: () => ({ title: "Cenník" }) },
});
